apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: Bucket
metadata:
  name: name
  namespace: namespace
spec:
  # accessFrom:  # AccessFrom defines an Access Control List for allowing cross-namespace references to this object.
    # namespaceSelectors:  # NamespaceSelectors is the list of namespace selectors to which this ACL applies. Items in this list are evaluated using a logical OR operation.
    # - matchLabels:  # MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
  bucketName: "string" # The bucket name.
  # ignore: "string" # Ignore overrides the set of excluded patterns in the .sourceignore format (which is the same as .gitignore). If not provided, a default will be used, consult the documentation for your version to find out what those are.
  # secretRef:  # The name of the secret containing authentication credentials for the Bucket.
    # name: "string" # Name of the referent.
  # suspend: true # This flag tells the controller to suspend the reconciliation of this source.
  # timeout: "string" # The timeout for download operations, defaults to 60s.
  endpoint: "string" # The bucket endpoint address.
  # insecure: true # Insecure allows connecting to a non-TLS S3 HTTP endpoint.
  interval: "string" # The interval at which to check for bucket updates.
  # provider: "string" # The S3 compatible storage provider name, default ('generic').
  # region: "string" # The bucket region.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: name
  namespace: namespace
spec:
  # accessFrom:  # AccessFrom specifies an Access Control List for allowing cross-namespace references to this object. NOTE: Not implemented, provisional as of https://github.com/fluxcd/flux2/pull/2092
    # namespaceSelectors:  # NamespaceSelectors is the list of namespace selectors to which this ACL applies. Items in this list are evaluated using a logical OR operation.
    # - matchLabels:  # MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
  # insecure: true # Insecure allows connecting to a non-TLS HTTP Endpoint.
  # region: "string" # Region of the Endpoint where the BucketName is located in.
  # secretRef:  # SecretRef specifies the Secret containing authentication credentials for the Bucket.
    # name: "string" # Name of the referent.
  # suspend: true # Suspend tells the controller to suspend the reconciliation of this Bucket.
  # timeout: "string" # Timeout for fetch operations, defaults to 60s.
  bucketName: "string" # BucketName is the name of the object storage bucket.
  endpoint: "string" # Endpoint is the object storage address the BucketName is located at.
  # ignore: "string" # Ignore overrides the set of excluded patterns in the .sourceignore format (which is the same as .gitignore). If not provided, a default will be used, consult the documentation for your version to find out what those are.
  interval: "string" # Interval at which the Bucket Endpoint is checked for updates. This interval is approximate and may be subject to jitter to ensure efficient use of resources.
  # provider: "string" # Provider of the object storage bucket. Defaults to 'generic', which expects an S3 (API) compatible object storage.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: name
  namespace: namespace
spec:
  # secretRef:  # SecretRef specifies the Secret containing authentication credentials for the GitRepository. For HTTPS repositories the Secret must contain 'username' and 'password' fields for basic auth or 'bearerToken' field for token auth. For SSH repositories the Secret must contain 'identity' and 'known_hosts' fields.
    # name: "string" # Name of the referent.
  # suspend: true # Suspend tells the controller to suspend the reconciliation of this GitRepository.
  # timeout: "string" # Timeout for Git operations like cloning, defaults to 60s.
  # verify:  # Verification specifies the configuration to verify the Git commit signature(s).
    # mode: "string" # Mode specifies which Git object(s) should be verified.  The variants "head" and "HEAD" both imply the same thing, i.e. verify the commit that the HEAD of the Git repository points to. The variant "head" solely exists to ensure backwards compatibility.
    # secretRef:  # SecretRef specifies the Secret containing the public keys of trusted Git authors.
      # name: "string" # Name of the referent.
  # ignore: "string" # Ignore overrides the set of excluded patterns in the .sourceignore format (which is the same as .gitignore). If not provided, a default will be used, consult the documentation for your version to find out what those are.
  # proxySecretRef:  # ProxySecretRef specifies the Secret containing the proxy configuration to use while communicating with the Git server.
    # name: "string" # Name of the referent.
  # recurseSubmodules: true # RecurseSubmodules enables the initialization of all submodules within the GitRepository as cloned from the URL, using their default settings.
  # ref:  # Reference specifies the Git reference to resolve and monitor for changes, defaults to the 'master' branch.
    # branch: "string" # Branch to check out, defaults to 'master' if no other field is defined.
    # commit: "string" # Commit SHA to check out, takes precedence over all reference fields.  This can be combined with Branch to shallow clone the branch, in which the commit is expected to exist.
    # name: "string" # Name of the reference to check out; takes precedence over Branch, Tag and SemVer.  It must be a valid Git reference: https://git-scm.com/docs/git-check-ref-format#_description Examples: "refs/heads/main", "refs/tags/v0.1.0", "refs/pull/420/head", "refs/merge-requests/1/head"
    # semver: "string" # SemVer tag expression to check out, takes precedence over Tag.
    # tag: "string" # Tag to check out, takes precedence over Branch.
  url: "string" # URL specifies the Git repository URL, it can be an HTTP/S or SSH address.
  # include:  # Include specifies a list of GitRepository resources which Artifacts should be included in the Artifact produced for this GitRepository.
  # - fromPath: "string" # FromPath specifies the path to copy contents from, defaults to the root of the Artifact.
    # repository:  # GitRepositoryRef specifies the GitRepository which Artifact contents must be included.
      # name: "string" # Name of the referent.
    # toPath: "string" # ToPath specifies the path to copy contents to, defaults to the name of the GitRepositoryRef.
  interval: "string" # Interval at which the GitRepository URL is checked for updates. This interval is approximate and may be subject to jitter to ensure efficient use of resources.
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: name
  namespace: namespace
spec:
  # gitImplementation: "string" # Determines which git client library to use. Defaults to go-git, valid values are ('go-git', 'libgit2').
  interval: "string" # The interval at which to check for repository updates.
  # ref:  # The Git reference to checkout and monitor for changes, defaults to master branch.
    # semver: "string" # The Git tag semver expression, takes precedence over Tag.
    # tag: "string" # The Git tag to checkout, takes precedence over Branch.
    # branch: "string" # The Git branch to checkout, defaults to master.
    # commit: "string" # The Git commit SHA to checkout, if specified Tag filters will be ignored.
  # secretRef:  # The secret name containing the Git credentials. For HTTPS repositories the secret must contain username and password fields. For SSH repositories the secret must contain identity and known_hosts fields.
    # name: "string" # Name of the referent.
  # timeout: "string" # The timeout for remote Git operations like cloning, defaults to 60s.
  # verify:  # Verify OpenPGP signature for the Git commit HEAD points to.
    # mode: "string" # Mode describes what git object should be verified, currently ('head').
    # secretRef:  # The secret name containing the public keys of all trusted Git authors.
      # name: "string" # Name of the referent.
  # accessFrom:  # AccessFrom defines an Access Control List for allowing cross-namespace references to this object.
    # namespaceSelectors:  # NamespaceSelectors is the list of namespace selectors to which this ACL applies. Items in this list are evaluated using a logical OR operation.
    # - matchLabels:  # MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
  # ignore: "string" # Ignore overrides the set of excluded patterns in the .sourceignore format (which is the same as .gitignore). If not provided, a default will be used, consult the documentation for your version to find out what those are.
  # include:  # Extra git repositories to map into the repository
  # - fromPath: "string" # The path to copy contents from, defaults to the root directory.
    # repository:  # Reference to a GitRepository to include.
      # name: "string" # Name of the referent.
    # toPath: "string" # The path to copy contents to, defaults to the name of the source ref.
  # recurseSubmodules: true # When enabled, after the clone is created, initializes all submodules within, using their default settings. This option is available only when using the 'go-git' GitImplementation.
  # suspend: true # This flag tells the controller to suspend the reconciliation of this source.
  url: "string" # The repository URL, can be a HTTP/S or SSH address.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: name
  namespace: namespace
spec:
  interval: "string" # Interval at which to check the GitRepository for updates.
  # recurseSubmodules: true # RecurseSubmodules enables the initialization of all submodules within the GitRepository as cloned from the URL, using their default settings.
  # secretRef:  # SecretRef specifies the Secret containing authentication credentials for the GitRepository. For HTTPS repositories the Secret must contain 'username' and 'password' fields for basic auth or 'bearerToken' field for token auth. For SSH repositories the Secret must contain 'identity' and 'known_hosts' fields.
    # name: "string" # Name of the referent.
  url: "string" # URL specifies the Git repository URL, it can be an HTTP/S or SSH address.
  # ref:  # Reference specifies the Git reference to resolve and monitor for changes, defaults to the 'master' branch.
    # tag: "string" # Tag to check out, takes precedence over Branch.
    # branch: "string" # Branch to check out, defaults to 'master' if no other field is defined.
    # commit: "string" # Commit SHA to check out, takes precedence over all reference fields.  This can be combined with Branch to shallow clone the branch, in which the commit is expected to exist.
    # name: "string" # Name of the reference to check out; takes precedence over Branch, Tag and SemVer.  It must be a valid Git reference: https://git-scm.com/docs/git-check-ref-format#_description Examples: "refs/heads/main", "refs/tags/v0.1.0", "refs/pull/420/head", "refs/merge-requests/1/head"
    # semver: "string" # SemVer tag expression to check out, takes precedence over Tag.
  # suspend: true # Suspend tells the controller to suspend the reconciliation of this GitRepository.
  # timeout: "string" # Timeout for Git operations like cloning, defaults to 60s.
  # verify:  # Verification specifies the configuration to verify the Git commit signature(s).
    # mode: "string" # Mode specifies what Git object should be verified, currently ('head').
    # secretRef:  # SecretRef specifies the Secret containing the public keys of trusted Git authors.
      # name: "string" # Name of the referent.
  # accessFrom:  # AccessFrom specifies an Access Control List for allowing cross-namespace references to this object. NOTE: Not implemented, provisional as of https://github.com/fluxcd/flux2/pull/2092
    # namespaceSelectors:  # NamespaceSelectors is the list of namespace selectors to which this ACL applies. Items in this list are evaluated using a logical OR operation.
    # - matchLabels:  # MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
  # gitImplementation: "string" # GitImplementation specifies which Git client library implementation to use. Defaults to 'go-git', valid values are ('go-git', 'libgit2'). Deprecated: gitImplementation is deprecated now that 'go-git' is the only supported implementation.
  # ignore: "string" # Ignore overrides the set of excluded patterns in the .sourceignore format (which is the same as .gitignore). If not provided, a default will be used, consult the documentation for your version to find out what those are.
  # include:  # Include specifies a list of GitRepository resources which Artifacts should be included in the Artifact produced for this GitRepository.
  # - fromPath: "string" # FromPath specifies the path to copy contents from, defaults to the root of the Artifact.
    # repository:  # GitRepositoryRef specifies the GitRepository which Artifact contents must be included.
      # name: "string" # Name of the referent.
    # toPath: "string" # ToPath specifies the path to copy contents to, defaults to the name of the GitRepositoryRef.
---
